Repository aukletio/Auklet-Releaser-C, pull requests merged in 2018-11, with the labels that each got.

#2 APM-1686: publish binaries to public S3 for all environments
  .devops/deploy.sh
  cmd/release/main.go
  config/config.go
  config/static.go
Labels: enhancement

#3 Fix versioning during deployment
  .devops/deploy.sh
Labels: bug

#4 Release Candidate Review
  .circleci/config.yml
  .devops/calculate-app-version.sh
  .devops/calculateChangelogs.js
  .devops/deploy.sh
  .devops/determineVersionChange.js
  .devops/licenses.js
  .devops/post-release.sh
  .devops/ssh-config-aukletio
  .devops/updateProdReleasePr.sh
  .devops/validate-pr.sh
  .devops/validatePr.js
  .esg
  cmd/release/main.go
  compose/auklet/Dockerfile
  config/config.go
  config/static.go
  docker-compose.yml
Labels: release

#5 Update instructions for bug reports
  README.md
  docs/CONTRIBUTING.md
Labels: devops

#6 Release Review
  .circleci/config.yml
  .devops/calculate-app-version.sh
  .devops/calculateChangelogs.js
  .devops/deploy.sh
  .devops/determineVersionChange.js
  .devops/licenses.js
  .devops/post-release.sh
  .devops/ssh-config-aukletio
  .devops/updateProdReleasePr.sh
  .devops/validate-pr.sh
  .devops/validatePr.js
  .esg
  cmd/release/main.go
  compose/auklet/Dockerfile
  config/config.go
  config/static.go
  docker-compose.yml
Labels: release
